project: VAE_Series
model: vae

optimizer: adam
learning_rate: !!float 1e-4
batch_size: !!int 256
epochs: !!int 30
train_iter: !!int 1000

log_iter: !!int 100
log_fig_iter: !!int 500
log_dir: ./log

save_fig: !!bool true
save_dir: ./outputs
checkpoint_dir: ./ckpts